"""empty message

Revision ID: 616a0b329937
Revises: 87b42d6aa2e7
Create Date: 2023-01-12 14:06:12.145307

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '616a0b329937'
down_revision = '87b42d6aa2e7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jwt_token',
    sa.Column('id', postgresql.UUID(as_uuid=True), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('refresh_token', sa.String(length=32), nullable=False),
    sa.Column('ttl', sa.DateTime(), server_default=sa.FetchedValue(), nullable=False),
    sa.Column('user_id', postgresql.UUID(as_uuid=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('refresh_token'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_jwt_token_id'), 'jwt_token', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_jwt_token_id'), table_name='jwt_token')
    op.drop_table('jwt_token')
    # ### end Alembic commands ###
