"""empty message

Revision ID: 7e15cbd63c89
Revises: cb1b18f342b8
Create Date: 2023-01-12 11:47:04.394880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e15cbd63c89'
down_revision = 'cb1b18f342b8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.String(length=32), nullable=True))
    op.create_unique_constraint('users_refresh_token_key', 'users', ['refresh_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_refresh_token_key', 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###
