version: "3.9"
services:     
  app:
    image: test-webtronics-task-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis  
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  postgres:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=testpassword
      - POSTGRES_DB=test_webtronics
    ports:
      - 5432:5432
    volumes:
      - test-data-volume:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U test -d test_webtronics
      interval: 10s
      timeout: 3s
      retries: 5

volumes:
  test-data-volume: