"""empty message

Revision ID: 7562329621b7
Revises: b36b97c1b3af
Create Date: 2023-01-11 00:19:15.219806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7562329621b7'
down_revision = 'b36b97c1b3af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
