"""empty message

Revision ID: 87b42d6aa2e7
Revises: 7e15cbd63c89
Create Date: 2023-01-12 13:58:54.793519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87b42d6aa2e7'
down_revision = '7e15cbd63c89'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('users_refresh_token_key', 'users', type_='unique')
    op.drop_column('users', 'refresh_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('refresh_token', sa.VARCHAR(length=32), autoincrement=False, nullable=True))
    op.create_unique_constraint('users_refresh_token_key', 'users', ['refresh_token'])
    # ### end Alembic commands ###
